//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSearch.HotelServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelModel", Namespace="http://schemas.datacontract.org/2004/07/SearchHotelWCF")]
    [System.SerializableAttribute()]
    public partial class HotelModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelId {
            get {
                return this.HotelIdField;
            }
            set {
                if ((this.HotelIdField.Equals(value) != true)) {
                    this.HotelIdField = value;
                    this.RaisePropertyChanged("HotelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName {
            get {
                return this.HotelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelNameField, value) != true)) {
                    this.HotelNameField = value;
                    this.RaisePropertyChanged("HotelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelRating {
            get {
                return this.HotelRatingField;
            }
            set {
                if ((this.HotelRatingField.Equals(value) != true)) {
                    this.HotelRatingField = value;
                    this.RaisePropertyChanged("HotelRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelServiceReference.IHotelSearch")]
    public interface IHotelSearch {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelSearch/GetAllHotels", ReplyAction="http://tempuri.org/IHotelSearch/GetAllHotelsResponse")]
        HotelSearch.HotelServiceReference.HotelModel[] GetAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelSearch/GetAllHotels", ReplyAction="http://tempuri.org/IHotelSearch/GetAllHotelsResponse")]
        System.Threading.Tasks.Task<HotelSearch.HotelServiceReference.HotelModel[]> GetAllHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelSearch/GetHotelById", ReplyAction="http://tempuri.org/IHotelSearch/GetHotelByIdResponse")]
        HotelSearch.HotelServiceReference.HotelModel GetHotelById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelSearch/GetHotelById", ReplyAction="http://tempuri.org/IHotelSearch/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<HotelSearch.HotelServiceReference.HotelModel> GetHotelByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelSearchChannel : HotelSearch.HotelServiceReference.IHotelSearch, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelSearchClient : System.ServiceModel.ClientBase<HotelSearch.HotelServiceReference.IHotelSearch>, HotelSearch.HotelServiceReference.IHotelSearch {
        
        public HotelSearchClient() {
        }
        
        public HotelSearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelSearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelSearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelSearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelSearch.HotelServiceReference.HotelModel[] GetAllHotels() {
            return base.Channel.GetAllHotels();
        }
        
        public System.Threading.Tasks.Task<HotelSearch.HotelServiceReference.HotelModel[]> GetAllHotelsAsync() {
            return base.Channel.GetAllHotelsAsync();
        }
        
        public HotelSearch.HotelServiceReference.HotelModel GetHotelById(int Id) {
            return base.Channel.GetHotelById(Id);
        }
        
        public System.Threading.Tasks.Task<HotelSearch.HotelServiceReference.HotelModel> GetHotelByIdAsync(int Id) {
            return base.Channel.GetHotelByIdAsync(Id);
        }
    }
}
